"""
Generates the connector bundle a testbed operator deploys: connector
properties, docker-compose, nginx vhost, a template metadata.json and a README.

Contains no data-lake credentials: the central connector supplies the (scoped)
data-lake destination in the transfer request, so the testbed never holds them.
The only secrets in the bundle are the passwords of the testbed's own Postgres
and S3 store, derived from the master secret so a regenerated bundle matches.
"""

import io
import json
import zipfile

from config import CENTRAL_CONNECTOR_URL
from testbed_store import derive_secret

IMAGE = "ghcr.io/6g-dali/6gdali-testbed-connector:latest"


def _properties(tb: dict, pg_password: str, asset_admin_key: str) -> str:
    return f"""# 6G-DALI testbed connector: {tb['name']}
# Generated by the 6G-DALI DataOps registry. Do not change the identity values:
# the central connector expects exactly these.

# --- Database -----------------------------------------------------------------
edc.datasource.default.url=jdbc:postgresql://db:5432/edc_provider
edc.datasource.default.user=edc_user
edc.datasource.default.password={pg_password}
edc.sql.schema.autocreate=true
edc.datasource.default.pool.maxIdleConnections=10
edc.datasource.default.pool.maxTotalConnections=20
edc.datasource.default.pool.minIdleConnections=3
edc.datasource.default.pool.testConnectionOnBorrow=true
edc.datasource.default.pool.testConnectionOnCreate=true
edc.datasource.default.pool.testConnectionWhileIdle=true
edc.sql.store.asset.datasource=default
edc.sql.store.contractdefinition.datasource=default
edc.sql.store.contractnegotiation.datasource=default
edc.sql.store.transferprocess.datasource=default
edc.sql.store.policydefinition.datasource=default
edc.sql.store.policymonitor.datasource=default

# --- Connector ----------------------------------------------------------------
edc.hostname=provider
edc.transfer.proxy.token.signer.privatekey.alias=private-key
edc.transfer.proxy.token.verifier.publickey.alias=public-key
web.http.port=18190
web.http.path=/api
web.http.management.port=18191
web.http.management.path=/management
web.http.protocol.port=18192
web.http.protocol.path=/protocol
web.http.control.port=18193
web.http.control.path=/control
edc.dataplane.http.sink.partition.size=1

# --- Identity (assigned by the registry) --------------------------------------
edc.participant.id={tb['participant_id']}
edc.ids.id={tb['ids_id']}
edc.experiment.prefix={tb['experiment_prefix']}
# Public URL other connectors use to reach this one (see nginx/ in this bundle).
edc.dsp.callback.address={tb['dsp_url']}
edc.dali.connector.url={CENTRAL_CONNECTOR_URL}

# --- CORS ---------------------------------------------------------------------
edc.web.rest.cors.enabled=true
edc.web.rest.cors.origins=*
edc.web.rest.cors.methods=GET,POST,PUT,DELETE,OPTIONS
edc.web.rest.cors.headers=origin,content-type,accept,authorization,x-api-key
edc.web.rest.cors.credentials=true

# --- Asset registration page ----------------------------------------------------
# Enables http(s)://<your-connector>/api/catalog/register-asset. The operator enters this
# key on the page to register the dataset bucket as an asset.
edc.catalog.ui.asset.admin.key={asset_admin_key}

# --- Catalogue API used by the connector's file source -------------------------
edc.external.api.url=https://dataspace.6gdali.eu/datasets
edc.external.api.key=yourRepoApiKey

# --- Transfer-completion messages (optional, testbed-internal) -----------------
# Uncomment and set to your own RabbitMQ to receive one message per transferred CSV.
#edc.rabbitmq.host=
#edc.rabbitmq.port=5672
#edc.rabbitmq.username=
#edc.rabbitmq.password=
#edc.rabbitmq.queue=ds_connector
"""


def _compose(tb: dict, s3_user: str, s3_password: str, pg_password: str) -> str:
    slug = tb["slug"]
    return f"""# 6G-DALI testbed connector stack: {tb['name']}
# The `rustfs` store and `rustfs-init` are optional: delete them and point the
# asset at your own S3-compatible store if you already have one.
services:

  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: edc_provider
      POSTGRES_USER: edc_user
      POSTGRES_PASSWORD: {pg_password}
    volumes:
      - DB_DATA:/var/lib/postgresql/data
    networks: [dali-net]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U edc_user -d edc_provider"]
      interval: 10s
      timeout: 5s
      retries: 5

  rustfs:
    image: rustfs/rustfs:latest
    restart: always
    command: server /data --console-address ":9001" --address ":9000"
    environment:
      RUSTFS_ROOT_USER: {s3_user}
      RUSTFS_ROOT_PASSWORD: {s3_password}
    ports:
      - "127.0.0.1:9000:9000"
      - "127.0.0.1:9001:9001"
    volumes:
      - S3_DATA:/data
    networks: [dali-net]
    healthcheck:
      test: ["CMD-SHELL", "curl -sf http://localhost:9000/health/live || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 15
      start_period: 10s

  rustfs-init:
    image: amazon/aws-cli:latest
    depends_on:
      rustfs:
        condition: service_healthy
    environment:
      AWS_ACCESS_KEY_ID: {s3_user}
      AWS_SECRET_ACCESS_KEY: {s3_password}
      AWS_DEFAULT_REGION: us-east-1
    entrypoint: >
      /bin/sh -c "aws --endpoint-url http://rustfs:9000 s3 mb s3://{slug}-datasets 2>/dev/null || true"
    networks: [dali-net]

  provider:
    image: {IMAGE}
    pull_policy: always
    restart: always
    depends_on:
      db:
        condition: service_healthy
      rustfs:
        condition: service_healthy
    # Published on the host for the nginx vhost in nginx/. Only /protocol (and
    # optionally /api) is routed publicly; the management API (18191) is not.
    ports:
      - "127.0.0.1:18190:18190"
      - "127.0.0.1:18191:18191"
      - "127.0.0.1:18192:18192"
    configs:
      - source: connector_config
        target: /usr/src/app/connector.properties
    volumes:
      - PROVIDER_DATA:/usr/src/app/data
    networks: [dali-net]

configs:
  connector_config:
    file: ./{slug}_connector.properties

networks:
  dali-net:
    driver: bridge

volumes:
  DB_DATA:
  S3_DATA:
  PROVIDER_DATA:
"""


def _nginx(tb: dict, domain: str) -> str:
    var = "edc_backend"
    return f"""# {tb['name']} EDC connector. Obtain a TLS certificate for {domain} (e.g. certbot) and
# add the usual listen 443 ssl / ssl_certificate lines.
#
#   /protocol* -> 18192 (DSP): must be public, the central connector calls it.
#   /api*      -> 18190 (health, connector UI): optional.
# The management API (18191) and control API (18193) are deliberately not published.
# The path is passed through untouched: the connector serves each API under its prefix.
map $uri ${var} {{
    default     http://127.0.0.1:18190;
    ~^/api      http://127.0.0.1:18190;
    ~^/protocol http://127.0.0.1:18192;
}}

server {{
    listen 80;
    server_name {domain};

    location ~ /.well-known {{
        root /var/www/html/;
        allow all;
    }}

    location / {{
        proxy_pass ${var};
        proxy_connect_timeout 420s;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_http_version 1.1;
        proxy_buffers 8 32k;
        proxy_buffer_size 64k;
    }}
}}
"""


def _metadata_template(tb: dict) -> str:
    return json.dumps({
        "title": "TODO dataset title",
        "description": "TODO what this dataset contains",
        "issued": "2026-01-01",
        "license": "CC-BY-4.0",
        "access_rights": "PUBLIC",
        "gdpr_compliant": True,
        "fair_compliant": True,
        "contains_pii": False,
        "sns_project_name": "6G-DALI",
        "produced_by": tb.get("produced_by_iri") or "TODO ask the platform administrator",
    }, indent=2) + "\n"


def _readme(tb: dict, domain: str) -> str:
    slug = tb["slug"]
    return f"""# {tb['name']}: 6G-DALI testbed connector

Identity assigned by the registry (do not change):

| | |
|---|---|
| edc.participant.id | `{tb['participant_id']}` |
| edc.experiment.prefix | `{tb['experiment_prefix']}` |
| edc.dsp.callback.address | `{tb['dsp_url']}` |

## Deploy

1. Create the DNS record for `{domain}` and install `nginx/{domain}.conf` with a TLS certificate.
2. `docker compose up -d`, then check `curl -s http://localhost:18190/api/check/health`.
3. Open `https://{domain}/api/catalog/register-asset` (or http://localhost:18190/api/catalog/register-asset), enter the
   admin key (`edc.catalog.ui.asset.admin.key` in the properties file) and register your bucket as an asset.
4. Tell the platform administrator the connector is up; they connect it from the DataOps UI.
5. Upload a dataset to the bucket: `<dataset>/metadata.json` first, then the CSV files.
   Use `template/metadata.json` as a starting point.

The local store (`rustfs`) holds your datasets in the bucket `{slug}-datasets`. Create an access
key for the connector in its console (http://localhost:9001); the data-lake credentials are
managed centrally and are not needed here.
"""


def build_bundle(tb: dict) -> bytes:
    slug = tb["slug"]
    domain = tb["dsp_url"].split("://", 1)[-1].split("/", 1)[0]
    pg = derive_secret(slug, "postgres")
    s3_user, s3_password = f"{slug}-admin", derive_secret(slug, "local-s3")
    files = {
        f"{slug}_connector.properties": _properties(tb, pg, derive_secret(slug, "asset-admin", length=32)),
        "docker-compose.yaml": _compose(tb, s3_user, s3_password, pg),
        f"nginx/{domain}.conf": _nginx(tb, domain),
        "template/metadata.json": _metadata_template(tb),
        "README.md": _readme(tb, domain),
    }
    buf = io.BytesIO()
    with zipfile.ZipFile(buf, "w", zipfile.ZIP_DEFLATED) as z:
        for name, content in files.items():
            z.writestr(f"connector-{slug}/{name}", content)
    return buf.getvalue()
